// Authentcation
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const FUTCH_PROFILE = "FUTCH_PROFILE";
export const FUTCH_MY_PROFILE = "FUTCH_MY_PROFILE";

//Activities
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const FETCH_CATEGORY_ACTIVITIES = "FETCH_CATEGORY_ACTIVITIES";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const ACTIVITY_DETAILS = "ACTIVITY_DETAILS";

//Activity CRUD
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
